flink:
  rest_bind_address: "0.0.0.0"
  rest_port: "8082"
  parallelism: 1
  jars:
    - "file:///opt/flink/opt/flink-connector-kafka-4.0.1-2.0.jar"
    - "file:///opt/kafka/libs/kafka-clients-4.1.1.jar"

kafka:
  bootstrap_servers: "localhost:9092"
  group_id: "watermark-processor"

topics:
  input: "span-events"
  output: "span-output"

watermark:
  strategy: "periodic"  # or "adwin"
