# Flink Configuration
flink.rest.bind.address=0.0.0.0
flink.rest.port=8081
flink.parallelism=1
flink.jars=file:///dependencies/*.jar

# Kafka Configuration
kafka.bootstrap.servers=localhost:9092
kafka.group.id=watermark-processor

# Topics Configuration
topics.input=span-events
topics.output=span-output

# Watermark Configuration
watermark.strategy=periodic
watermark.auto.interval=100
watermark.max.out.of.orderness.ms=1000
